package com.example.scoreboard.domain;

public enum ErrorCode {
  INVALID_TEAM_NAME,
  SAME_TEAM,
  DUPLICATE_ACTIVE_TEAM,
  INVALID_SCORE,
  MATCH_NOT_FOUND,
  MATCH_ALREADY_FINISHED,
  INVALID_MATCH_OPERATION
}
